services:

  app:
    image: ghcr.io/aleksey925/runtime-config:dev
    restart: on-failure:10
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "8080:8080"
    links:
      - db
    command: serve

  migration:
    image: ghcr.io/aleksey925/runtime-config:dev
    restart: on-failure:10
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    links:
      - db
    entrypoint: /bin/bash -c 'alembic upgrade head'

  db:
    image: postgres:14-alpine
    restart: on-failure:10
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./.volumes/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
