services:

  app:
    image: ghcr.io/aleksey925/runtime-config:latest
    restart: on-failure:10
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    entrypoint: /bin/bash -c 'alembic upgrade head && runtime-config serve'

  db:
    image: postgres:14-alpine
    restart: on-failure:10
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db:
